package com.openlogh.dto

import com.openlogh.entity.*
import java.time.OffsetDateTime

data class OfficerResponse(
    val id: Long,
    val sessionId: Long,
    val userId: Long?,
    val name: String,
    val factionId: Long,
    val planetId: Long,
    val fleetId: Long,
    val npcState: Short,
    val npcOrg: Long?,
    val affinity: Short,
    val birthYear: Short,
    val deathYear: Short,
    val picture: String,
    val imageServer: Short,
    val leadership: Short,
    val leadershipExp: Short,
    val command: Short,
    val commandExp: Short,
    val intelligence: Short,
    val intelligenceExp: Short,
    val politics: Short,
    val politicsExp: Short,
    val administration: Short,
    val administrationExp: Short,
    val mobility: Short,
    val mobilityExp: Short,
    val attack: Short,
    val attackExp: Short,
    val defense: Short,
    val defenseExp: Short,
    val dex1: Int,
    val dex2: Int,
    val dex3: Int,
    val dex4: Int,
    val dex5: Int,
    val injury: Short,
    val experience: Int,
    val dedication: Int,
    val rank: Short,
    val stationedSystem: Int,
    val permission: String,
    val funds: Int,
    val supplies: Int,
    val ships: Int,
    val shipClass: Short,
    val training: Short,
    val morale: Short,
    val flagshipCode: String,
    val equipCode: String,
    val engineCode: String,
    val accessoryCode: String,
    val ownerName: String,
    val newmsg: Short,
    val turnTime: OffsetDateTime,
    val recentWarTime: OffsetDateTime?,
    val makeLimit: Short,
    val killTurn: Short?,
    val blockState: Short,
    val dedLevel: Short,
    val expLevel: Short,
    val age: Short,
    val startAge: Short,
    val belong: Short,
    val betray: Short,
    val personalCode: String,
    val specialCode: String,
    val specAge: Short,
    val special2Code: String,
    val spec2Age: Short,
    val defenceTrain: Short,
    val tournamentState: Short,
    val commandPoints: Int,
    val commandEndTime: OffsetDateTime?,
    val lastTurn: Map<String, Any>,
    val meta: Map<String, Any>,
    val penalty: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Officer) = OfficerResponse(
            id = e.id,
            sessionId = e.sessionId,
            userId = e.userId,
            name = e.name,
            factionId = e.factionId,
            planetId = e.planetId,
            fleetId = e.fleetId,
            npcState = e.npcState,
            npcOrg = e.npcOrg,
            affinity = e.affinity,
            birthYear = e.birthYear,
            deathYear = e.deathYear,
            picture = e.picture,
            imageServer = e.imageServer,
            leadership = e.leadership,
            leadershipExp = e.leadershipExp,
            command = e.command,
            commandExp = e.commandExp,
            intelligence = e.intelligence,
            intelligenceExp = e.intelligenceExp,
            politics = e.politics,
            politicsExp = e.politicsExp,
            administration = e.administration,
            administrationExp = e.administrationExp,
            mobility = e.mobility,
            mobilityExp = e.mobilityExp,
            attack = e.attack,
            attackExp = e.attackExp,
            defense = e.defense,
            defenseExp = e.defenseExp,
            dex1 = e.dex1,
            dex2 = e.dex2,
            dex3 = e.dex3,
            dex4 = e.dex4,
            dex5 = e.dex5,
            injury = e.injury,
            experience = e.experience,
            dedication = e.dedication,
            rank = e.rank,
            stationedSystem = e.stationedSystem,
            permission = e.permission,
            funds = e.funds,
            supplies = e.supplies,
            ships = e.ships,
            shipClass = e.shipClass,
            training = e.training,
            morale = e.morale,
            flagshipCode = e.flagshipCode,
            equipCode = e.equipCode,
            engineCode = e.engineCode,
            accessoryCode = e.accessoryCode,
            ownerName = e.ownerName,
            newmsg = e.newmsg,
            turnTime = e.turnTime,
            recentWarTime = e.recentWarTime,
            makeLimit = e.makeLimit,
            killTurn = e.killTurn,
            blockState = e.blockState,
            dedLevel = e.dedLevel,
            expLevel = e.expLevel,
            age = e.age,
            startAge = e.startAge,
            belong = e.belong,
            betray = e.betray,
            personalCode = e.personalCode,
            specialCode = e.specialCode,
            specAge = e.specAge,
            special2Code = e.special2Code,
            spec2Age = e.spec2Age,
            defenceTrain = e.defenceTrain,
            tournamentState = e.tournamentState,
            commandPoints = e.commandPoints,
            commandEndTime = e.commandEndTime,
            lastTurn = e.lastTurn,
            meta = e.meta,
            penalty = e.penalty,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

data class FactionResponse(
    val id: Long,
    val sessionId: Long,
    val name: String,
    val abbreviation: String,
    val color: String,
    val capitalPlanetId: Long?,
    val funds: Int,
    val supplies: Int,
    val taxRate: Short,
    val conscriptionRate: Short,
    val conscriptionRateTmp: Short,
    val secretLimit: Short,
    val supremeCommanderId: Long,
    val scoutLevel: Short,
    val warState: Short,
    val strategicCmdLimit: Short,
    val surrenderLimit: Short,
    val techLevel: Float,
    val militaryPower: Int,
    val factionRank: Short,
    val factionType: String,
    val spy: Map<String, Any>,
    val meta: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Faction) = FactionResponse(
            id = e.id,
            sessionId = e.sessionId,
            name = e.name,
            abbreviation = e.abbreviation,
            color = e.color,
            capitalPlanetId = e.capitalPlanetId,
            funds = e.funds,
            supplies = e.supplies,
            taxRate = e.taxRate,
            conscriptionRate = e.conscriptionRate,
            conscriptionRateTmp = e.conscriptionRateTmp,
            secretLimit = e.secretLimit,
            supremeCommanderId = e.supremeCommanderId,
            scoutLevel = e.scoutLevel,
            warState = e.warState,
            strategicCmdLimit = e.strategicCmdLimit,
            surrenderLimit = e.surrenderLimit,
            techLevel = e.techLevel,
            militaryPower = e.militaryPower,
            factionRank = e.factionRank,
            factionType = e.factionType,
            spy = e.spy,
            meta = e.meta,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

data class PlanetResponse(
    val id: Long,
    val sessionId: Long,
    val name: String,
    val level: Short,
    val factionId: Long,
    val supplyState: Short,
    val frontState: Short,
    val population: Int,
    val populationMax: Int,
    val production: Int,
    val productionMax: Int,
    val commerce: Int,
    val commerceMax: Int,
    val security: Int,
    val securityMax: Int,
    val approval: Float,
    val tradeRoute: Int,
    val dead: Int,
    val orbitalDefense: Int,
    val orbitalDefenseMax: Int,
    val fortress: Int,
    val fortressMax: Int,
    val garrisonSet: Int,
    val state: Short,
    val region: Short,
    val term: Short,
    val conflict: Map<String, Any>,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Planet, regionOverride: Short? = null) = PlanetResponse(
            id = e.id,
            sessionId = e.sessionId,
            name = e.name,
            level = e.level,
            factionId = e.factionId,
            supplyState = e.supplyState,
            frontState = e.frontState,
            population = e.population,
            populationMax = e.populationMax,
            production = e.production,
            productionMax = e.productionMax,
            commerce = e.commerce,
            commerceMax = e.commerceMax,
            security = e.security,
            securityMax = e.securityMax,
            approval = e.approval,
            tradeRoute = e.tradeRoute,
            dead = e.dead,
            orbitalDefense = e.orbitalDefense,
            orbitalDefenseMax = e.orbitalDefenseMax,
            fortress = e.fortress,
            fortressMax = e.fortressMax,
            garrisonSet = e.garrisonSet,
            state = e.state,
            region = regionOverride ?: e.region,
            term = e.term,
            conflict = e.conflict,
            meta = e.meta,
        )
    }
}

data class SessionStateResponse(
    val id: Short,
    val name: String,
    val scenarioCode: String,
    val commitSha: String,
    val gameVersion: String,
    val currentYear: Short,
    val currentMonth: Short,
    val tickSeconds: Int,
    val realtimeMode: Boolean,
    val commandPointRegenRate: Int,
    val config: Map<String, Any>,
    val meta: Map<String, Any>,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: SessionState) = SessionStateResponse(
            id = e.id,
            name = e.name,
            scenarioCode = e.scenarioCode,
            commitSha = e.commitSha,
            gameVersion = e.gameVersion,
            currentYear = e.currentYear,
            currentMonth = e.currentMonth,
            tickSeconds = e.tickSeconds,
            realtimeMode = e.realtimeMode,
            commandPointRegenRate = e.commandPointRegenRate,
            config = e.config,
            meta = e.meta,
            updatedAt = e.updatedAt,
        )
    }
}


data class MessageResponse(
    val id: Long,
    val sessionId: Long,
    val mailboxCode: String,
    val mailboxType: String,
    val messageType: String,
    val srcId: Long?,
    val destId: Long?,
    val sentAt: OffsetDateTime,
    val validUntil: OffsetDateTime?,
    val payload: Map<String, Any>,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Message) = MessageResponse(
            id = e.id,
            sessionId = e.sessionId,
            mailboxCode = e.mailboxCode,
            mailboxType = e.mailboxType,
            messageType = e.messageType,
            srcId = e.srcId,
            destId = e.destId,
            sentAt = e.sentAt,
            validUntil = e.validUntil,
            payload = e.payload,
            meta = e.meta,
        )
    }
}

data class OfficerTurnResponse(
    val id: Long,
    val sessionId: Long,
    val officerId: Long,
    val turnIdx: Short,
    val actionCode: String,
    val arg: Map<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: OfficerTurn) = OfficerTurnResponse(
            id = e.id,
            sessionId = e.sessionId,
            officerId = e.officerId,
            turnIdx = e.turnIdx,
            actionCode = e.actionCode,
            arg = e.arg,
            brief = e.brief,
            createdAt = e.createdAt,
        )
    }
}

data class FactionTurnResponse(
    val id: Long,
    val sessionId: Long,
    val factionId: Long,
    val officerLevel: Short,
    val turnIdx: Short,
    val actionCode: String,
    val arg: Map<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: FactionTurn) = FactionTurnResponse(
            id = e.id,
            sessionId = e.sessionId,
            factionId = e.factionId,
            officerLevel = e.officerLevel,
            turnIdx = e.turnIdx,
            actionCode = e.actionCode,
            arg = e.arg,
            brief = e.brief,
            createdAt = e.createdAt,
        )
    }
}

data class BestOfficerResponse(
    val id: Long,
    val sessionId: Long,
    val name: String,
    val factionId: Long,
    val npcState: Short,
    val picture: String,
    val leadership: Short,
    val command: Short,
    val intelligence: Short,
    val politics: Short,
    val administration: Short,
    val experience: Int,
    val dedication: Int,
    val dex1: Int,
    val dex2: Int,
    val dex3: Int,
    val dex4: Int,
    val dex5: Int,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Officer) = BestOfficerResponse(
            id = e.id,
            sessionId = e.sessionId,
            name = e.name,
            factionId = e.factionId,
            npcState = e.npcState,
            picture = e.picture,
            leadership = e.leadership,
            command = e.command,
            intelligence = e.intelligence,
            politics = e.politics,
            administration = e.administration,
            experience = e.experience,
            dedication = e.dedication,
            dex1 = e.dex1,
            dex2 = e.dex2,
            dex3 = e.dex3,
            dex4 = e.dex4,
            dex5 = e.dex5,
            meta = e.meta,
        )
    }
}

data class RecordResponse(
    val id: Long,
    val sessionId: Long,
    val recordType: String,
    val srcId: Long?,
    val destId: Long?,
    val year: Int,
    val month: Int,
    val payload: Map<String, Any>,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Record) = RecordResponse(
            id = e.id,
            sessionId = e.sessionId,
            recordType = e.recordType,
            srcId = e.srcId,
            destId = e.destId,
            year = e.year,
            month = e.month,
            payload = e.payload,
            createdAt = e.createdAt,
        )
    }
}
