package com.openlogh.dto

import com.openlogh.entity.*
import java.time.OffsetDateTime

data class GeneralResponse(
    val id: Long,
    val worldId: Long,
    val userId: Long?,
    val name: String,
    val nationId: Long,
    val cityId: Long,
    val troopId: Long,
    val npcState: Short,
    val npcOrg: Long?,
    val affinity: Short,
    val bornYear: Short,
    val deadYear: Short,
    val picture: String,
    val imageServer: Short,
    val leadership: Short,
    val leadershipExp: Short,
    val strength: Short,
    val strengthExp: Short,
    val intel: Short,
    val intelExp: Short,
    val politics: Short,
    val politicsExp: Short,
    val charm: Short,
    val charmExp: Short,
    val dex1: Int,
    val dex2: Int,
    val dex3: Int,
    val dex4: Int,
    val dex5: Int,
    val injury: Short,
    val experience: Int,
    val dedication: Int,
    val officerLevel: Short,
    val officerPlanet: Int,
    val permission: String,
    val gold: Int,
    val rice: Int,
    val crew: Int,
    val crewType: Short,
    val train: Short,
    val atmos: Short,
    val weaponCode: String,
    val bookCode: String,
    val horseCode: String,
    val itemCode: String,
    val ownerName: String,
    val newmsg: Short,
    val turnTime: OffsetDateTime,
    val recentWarTime: OffsetDateTime?,
    val makeLimit: Short,
    val killTurn: Short?,
    val blockState: Short,
    val dedLevel: Short,
    val expLevel: Short,
    val age: Short,
    val startAge: Short,
    val belong: Short,
    val betray: Short,
    val personalCode: String,
    val specialCode: String,
    val specAge: Short,
    val special2Code: String,
    val spec2Age: Short,
    val defenceTrain: Short,
    val tournamentState: Short,
    val commandPoints: Int,
    val commandEndTime: OffsetDateTime?,
    val posX: Float,
    val posY: Float,
    val destX: Float?,
    val destY: Float?,
    val lastTurn: Map<String, Any>,
    val meta: Map<String, Any>,
    val penalty: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Officer) = GeneralResponse(
            id = e.id,
            worldId = e.sessionId,
            userId = e.userId,
            name = e.name,
            nationId = e.factionId,
            cityId = e.planetId,
            troopId = e.fleetId,
            npcState = e.npcState,
            npcOrg = e.npcOrg,
            affinity = e.affinity,
            bornYear = e.bornYear,
            deadYear = e.deadYear,
            picture = e.picture,
            imageServer = e.imageServer,
            leadership = e.leadership,
            leadershipExp = e.leadershipExp,
            strength = e.command,
            strengthExp = e.commandExp,
            intel = e.intelligence,
            intelExp = e.intelligenceExp,
            politics = e.politics,
            politicsExp = e.politicsExp,
            charm = e.administration,
            charmExp = e.administrationExp,
            dex1 = e.dex1,
            dex2 = e.dex2,
            dex3 = e.dex3,
            dex4 = e.dex4,
            dex5 = e.dex5,
            injury = e.injury,
            experience = e.experience,
            dedication = e.dedication,
            officerLevel = e.officerLevel,
            officerPlanet = e.officerPlanet,
            permission = e.permission,
            gold = e.funds,
            rice = e.supplies,
            crew = e.ships,
            crewType = e.shipClass,
            train = e.training,
            atmos = e.morale,
            weaponCode = e.flagshipCode,
            bookCode = e.equipCode,
            horseCode = e.engineCode,
            itemCode = e.accessoryCode,
            ownerName = e.ownerName,
            newmsg = e.newmsg,
            turnTime = e.turnTime,
            recentWarTime = e.recentWarTime,
            makeLimit = e.makeLimit,
            killTurn = e.killTurn,
            blockState = e.blockState,
            dedLevel = e.dedLevel,
            expLevel = e.expLevel,
            age = e.age,
            startAge = e.startAge,
            belong = e.belong,
            betray = e.betray,
            personalCode = e.personalCode,
            specialCode = e.specialCode,
            specAge = e.specAge,
            special2Code = e.special2Code,
            spec2Age = e.spec2Age,
            defenceTrain = e.defenceTrain,
            tournamentState = e.tournamentState,
            commandPoints = e.commandPoints,
            commandEndTime = e.commandEndTime,
            posX = e.posX,
            posY = e.posY,
            destX = e.destX,
            destY = e.destY,
            lastTurn = e.lastTurn,
            meta = e.meta,
            penalty = e.penalty,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

data class NationResponse(
    val id: Long,
    val worldId: Long,
    val name: String,
    val abbreviation: String,
    val color: String,
    val capitalCityId: Long?,
    val gold: Int,
    val rice: Int,
    val bill: Short,
    val rate: Short,
    val rateTmp: Short,
    val secretLimit: Short,
    val chiefGeneralId: Long,
    val scoutLevel: Short,
    val warState: Short,
    val strategicCmdLimit: Short,
    val surrenderLimit: Short,
    val tech: Float,
    val power: Int,
    val level: Short,
    val typeCode: String,
    val spy: Map<String, Any>,
    val meta: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Faction) = NationResponse(
            id = e.id,
            worldId = e.sessionId,
            name = e.name,
            abbreviation = e.abbreviation,
            color = e.color,
            capitalCityId = e.capitalPlanetId,
            gold = e.funds,
            rice = e.supplies,
            bill = e.taxRate,
            rate = e.conscriptionRate,
            rateTmp = e.conscriptionRateTmp,
            secretLimit = e.secretLimit,
            chiefGeneralId = e.chiefOfficerId,
            scoutLevel = e.scoutLevel,
            warState = e.warState,
            strategicCmdLimit = e.strategicCmdLimit,
            surrenderLimit = e.surrenderLimit,
            tech = e.techLevel,
            power = e.militaryPower,
            level = e.factionRank,
            typeCode = e.factionType,
            spy = e.spy,
            meta = e.meta,
            createdAt = e.createdAt,
            updatedAt = e.updatedAt,
        )
    }
}

data class CityResponse(
    val id: Long,
    val worldId: Long,
    val name: String,
    val level: Short,
    val nationId: Long,
    val supplyState: Short,
    val frontState: Short,
    val pop: Int,
    val popMax: Int,
    val agri: Int,
    val agriMax: Int,
    val comm: Int,
    val commMax: Int,
    val secu: Int,
    val secuMax: Int,
    val trust: Float,
    val trade: Int,
    val dead: Int,
    val def: Int,
    val defMax: Int,
    val wall: Int,
    val wallMax: Int,
    val officerSet: Int,
    val state: Short,
    val region: Short,
    val term: Short,
    val conflict: Map<String, Any>,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Planet, regionOverride: Short? = null) = CityResponse(
            id = e.id,
            worldId = e.sessionId,
            name = e.name,
            level = e.level,
            nationId = e.factionId,
            supplyState = e.supplyState,
            frontState = e.frontState,
            pop = e.population,
            popMax = e.populationMax,
            agri = e.production,
            agriMax = e.productionMax,
            comm = e.commerce,
            commMax = e.commerceMax,
            secu = e.security,
            secuMax = e.securityMax,
            trust = e.approval,
            trade = e.tradeRoute,
            dead = e.dead,
            def = e.orbitalDefense,
            defMax = e.orbitalDefenseMax,
            wall = e.fortress,
            wallMax = e.fortressMax,
            officerSet = e.officerSet,
            state = e.state,
            region = regionOverride ?: e.region,
            term = e.term,
            conflict = e.conflict,
            meta = e.meta,
        )
    }
}

data class WorldStateResponse(
    val id: Short,
    val name: String,
    val scenarioCode: String,
    val commitSha: String,
    val gameVersion: String,
    val currentYear: Short,
    val currentMonth: Short,
    val tickSeconds: Int,
    val realtimeMode: Boolean,
    val commandPointRegenRate: Int,
    val config: Map<String, Any>,
    val meta: Map<String, Any>,
    val updatedAt: OffsetDateTime,
) {
    companion object {
        fun from(e: SessionState) = WorldStateResponse(
            id = e.id,
            name = e.name,
            scenarioCode = e.scenarioCode,
            commitSha = e.commitSha,
            gameVersion = e.gameVersion,
            currentYear = e.currentYear,
            currentMonth = e.currentMonth,
            tickSeconds = e.tickSeconds,
            realtimeMode = e.realtimeMode,
            commandPointRegenRate = e.commandPointRegenRate,
            config = e.config,
            meta = e.meta,
            updatedAt = e.updatedAt,
        )
    }
}

data class TroopResponse(
    val id: Long,
    val worldId: Long,
    val leaderGeneralId: Long,
    val nationId: Long,
    val name: String,
    val meta: Map<String, Any>,
    val createdAt: OffsetDateTime,
    val turnTime: OffsetDateTime? = null,
    val reservedCommandBrief: String? = null,
) {
    companion object {
        fun from(e: Fleet) = TroopResponse(
            id = e.id,
            worldId = e.sessionId,
            leaderGeneralId = e.leaderOfficerId,
            nationId = e.factionId,
            name = e.name,
            meta = e.meta,
            createdAt = e.createdAt,
        )
    }
}

data class MessageResponse(
    val id: Long,
    val worldId: Long,
    val mailboxCode: String,
    val mailboxType: String,
    val messageType: String,
    val srcId: Long?,
    val destId: Long?,
    val sentAt: OffsetDateTime,
    val validUntil: OffsetDateTime?,
    val payload: Map<String, Any>,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Message) = MessageResponse(
            id = e.id,
            worldId = e.sessionId,
            mailboxCode = e.mailboxCode,
            mailboxType = e.mailboxType,
            messageType = e.messageType,
            srcId = e.srcId,
            destId = e.destId,
            sentAt = e.sentAt,
            validUntil = e.validUntil,
            payload = e.payload,
            meta = e.meta,
        )
    }
}

data class GeneralTurnResponse(
    val id: Long,
    val worldId: Long,
    val generalId: Long,
    val turnIdx: Short,
    val actionCode: String,
    val arg: Map<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: OfficerTurn) = GeneralTurnResponse(
            id = e.id,
            worldId = e.sessionId,
            generalId = e.officerId,
            turnIdx = e.turnIdx,
            actionCode = e.actionCode,
            arg = e.arg,
            brief = e.brief,
            createdAt = e.createdAt,
        )
    }
}

data class NationTurnResponse(
    val id: Long,
    val worldId: Long,
    val nationId: Long,
    val officerLevel: Short,
    val turnIdx: Short,
    val actionCode: String,
    val arg: Map<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: FactionTurn) = NationTurnResponse(
            id = e.id,
            worldId = e.sessionId,
            nationId = e.factionId,
            officerLevel = e.officerLevel,
            turnIdx = e.turnIdx,
            actionCode = e.actionCode,
            arg = e.arg,
            brief = e.brief,
            createdAt = e.createdAt,
        )
    }
}

data class BestGeneralResponse(
    val id: Long,
    val worldId: Long,
    val name: String,
    val nationId: Long,
    val npcState: Short,
    val picture: String,
    val leadership: Short,
    val strength: Short,
    val intel: Short,
    val politics: Short,
    val charm: Short,
    val experience: Int,
    val dedication: Int,
    val dex1: Int,
    val dex2: Int,
    val dex3: Int,
    val dex4: Int,
    val dex5: Int,
    val meta: Map<String, Any>,
) {
    companion object {
        fun from(e: Officer) = BestGeneralResponse(
            id = e.id,
            worldId = e.sessionId,
            name = e.name,
            nationId = e.factionId,
            npcState = e.npcState,
            picture = e.picture,
            leadership = e.leadership,
            strength = e.command,
            intel = e.intelligence,
            politics = e.politics,
            charm = e.administration,
            experience = e.experience,
            dedication = e.dedication,
            dex1 = e.dex1,
            dex2 = e.dex2,
            dex3 = e.dex3,
            dex4 = e.dex4,
            dex5 = e.dex5,
            meta = e.meta,
        )
    }
}

data class RecordResponse(
    val id: Long,
    val worldId: Long,
    val recordType: String,
    val srcId: Long?,
    val destId: Long?,
    val year: Int,
    val month: Int,
    val payload: Map<String, Any>,
    val createdAt: OffsetDateTime,
) {
    companion object {
        fun from(e: Record) = RecordResponse(
            id = e.id,
            worldId = e.sessionId,
            recordType = e.recordType,
            srcId = e.srcId,
            destId = e.destId,
            year = e.year,
            month = e.month,
            payload = e.payload,
            createdAt = e.createdAt,
        )
    }
}
