version: '3.2'

services:
  db:
    build: ./db
    restart: always
    volumes:
      - db:/var/lib/mysql
    env_file:
      - account.env
      - game.env

  web:
    build: ./web
    restart: always
    ports:
      - "9080:80"
    volumes:
      - ../legacy-core:/var/www/html/sam:ro

  app:
    build: ./app
    restart: always
    volumes:
      - ../legacy-core:/var/www/html/sam
    env_file:
      - game.env
    depends_on:
      - db
      - web

  install:
    build: ./install
    restart: "no"
    volumes:
      - ../legacy-core:/var/www/html/sam
    env_file:
      - account.env
      - game.env
    depends_on:
      - app
      - db
      - web

  cron:
    build: ./cron
    restart: always
    volumes:
      - ../legacy-core:/var/www/html/sam
    depends_on:
      - app

volumes:
  db:
