version: '3.2'

services:
  db:
    ports:
      - 3306:3306
      #For DEV. Expose MySQL port
    volumes:
      - type: bind
        source: ~/dev_sam/db
        target: /var/lib/mysql

  web:
    build:
      args:
        UID: 1000
        GID: 1000
        #For DEV. Set UID of www-data as first local user
    ports:
      - 8084:80
      #For DEV. Export Web port.
    volumes:
      - type: bind
        source: ~/dev_sam/app
        target: /var/www/html
        #For DEV. Set app path as local directory
      - type: bind
        source: ~/dev_sam/board
        target: /var/www/board

  app:
    build:
      args:
        UID: 1000
        GID: 1000
    volumes:
      - type: bind
        source: ~/dev_sam/app
        target: /var/www/html

  board:
    build:
      args:
        UID: 1000
        GID: 1000
    volumes:
      - type: bind
        source: ~/dev_sam/board
        target: /var/www/board

  install:
    volumes:
      - type: bind
        source: ~/dev_sam/app
        target: /var/www/html

  cron:
    build: ./cron
    restart: "no"
    #For DEV. Disable cron
    entrypoint: ["echo", "Service cron disabled"]

    volumes:
      - type: bind
        source: ~/dev_sam/app
        target: /var/www/html
    depends_on:
      - app

  backup:
    restart: "no"
    volumes:
      #- type: bind
      #  source: ~/dev_sam/backup
      #  target: /var/backup
      - type: bind
        read_only: true
        source: ~/dev_sam/app
        target: /var/www/html
      - type: bind
        read_only: true
        source: ~/dev_sam/board
        target: /var/www/board
