package com.openlogh.engine.turn.cqrs.memory

import java.time.OffsetDateTime

data class InMemoryWorldState(
    val sessionId: Long,
    val officers: MutableMap<Long, OfficerSnapshot> = mutableMapOf(),
    val planets: MutableMap<Long, PlanetSnapshot> = mutableMapOf(),
    val factions: MutableMap<Long, FactionSnapshot> = mutableMapOf(),
    val fleets: MutableMap<Long, FleetSnapshot> = mutableMapOf(),
    val diplomacies: MutableMap<Long, DiplomacySnapshot> = mutableMapOf(),
    val officerTurnsByOfficerId: MutableMap<Long, MutableList<OfficerTurnSnapshot>> = mutableMapOf(),
    val factionTurnsByFactionAndLevel: MutableMap<FactionTurnKey, MutableList<FactionTurnSnapshot>> = mutableMapOf(),
)

data class FactionTurnKey(
    val factionId: Long,
    val officerLevel: Short,
)

data class OfficerSnapshot(
    val id: Long,
    val sessionId: Long,
    val userId: Long?,
    val name: String,
    var factionId: Long,
    var planetId: Long,
    var fleetId: Long,
    var npcState: Short,
    var npcOrg: Long?,
    var affinity: Short,
    var bornYear: Short,
    var deadYear: Short,
    var picture: String,
    var imageServer: Short,
    var leadership: Short,
    var leadershipExp: Short,
    var command: Short,
    var commandExp: Short,
    var intelligence: Short,
    var intelligenceExp: Short,
    var politics: Short,
    var politicsExp: Short,
    var administration: Short,
    var administrationExp: Short,
    var mobility: Short,
    var mobilityExp: Short,
    var attack: Short,
    var attackExp: Short,
    var defense: Short,
    var defenseExp: Short,
    var dex1: Int,
    var dex2: Int,
    var dex3: Int,
    var dex4: Int,
    var dex5: Int,
    var dex6: Int,
    var dex7: Int,
    var dex8: Int,
    var injury: Short,
    var experience: Int,
    var dedication: Int,
    var officerLevel: Short,
    var officerCity: Int,
    var permission: String,
    var funds: Int,
    var supplies: Int,
    var ships: Int,
    var shipClass: Short,
    var training: Short,
    var morale: Short,
    var flagshipCode: String,
    var equipCode: String,
    var engineCode: String,
    var accessoryCode: String,
    var ownerName: String,
    var newmsg: Short,
    var turnTime: OffsetDateTime,
    var recentWarTime: OffsetDateTime?,
    var makeLimit: Short,
    var killTurn: Short?,
    var blockState: Short,
    var dedLevel: Short,
    var expLevel: Short,
    var age: Short,
    var startAge: Short,
    var belong: Short,
    var betray: Short,
    var personalCode: String,
    var specialCode: String,
    var specAge: Short,
    var special2Code: String,
    var spec2Age: Short,
    var defenceTrain: Short,
    var tournamentState: Short,
    var commandPoints: Int,
    var commandEndTime: OffsetDateTime?,
    var posX: Float,
    var posY: Float,
    var destX: Float?,
    var destY: Float?,
    var lastTurn: MutableMap<String, Any>,
    var meta: MutableMap<String, Any>,
    var penalty: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
    var updatedAt: OffsetDateTime,
)

data class PlanetSnapshot(
    val id: Long,
    val sessionId: Long,
    val name: String,
    val mapCityId: Int,
    var level: Short,
    var factionId: Long,
    var supplyState: Short,
    var frontState: Short,
    var population: Int,
    var populationMax: Int,
    var production: Int,
    var productionMax: Int,
    var commerce: Int,
    var commerceMax: Int,
    var security: Int,
    var securityMax: Int,
    var approval: Float,
    var tradeRoute: Int,
    var dead: Int,
    var orbitalDefense: Int,
    var orbitalDefenseMax: Int,
    var fortress: Int,
    var fortressMax: Int,
    var officerSet: Int,
    var state: Short,
    var region: Short,
    var term: Short,
    var conflict: MutableMap<String, Any>,
    var meta: MutableMap<String, Any>,
)

data class FactionSnapshot(
    val id: Long,
    val sessionId: Long,
    var name: String,
    var abbreviation: String,
    var color: String,
    var capitalPlanetId: Long?,
    var funds: Int,
    var supplies: Int,
    var taxRate: Short,
    var conscriptionRate: Short,
    var conscriptionRateTmp: Short,
    var secretLimit: Short,
    var chiefOfficerId: Long,
    var scoutLevel: Short,
    var warState: Short,
    var strategicCmdLimit: Short,
    var surrenderLimit: Short,
    var techLevel: Float,
    var militaryPower: Int,
    var officerCount: Int,
    var factionRank: Short,
    var factionType: String,
    var spy: MutableMap<String, Any>,
    var meta: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
    var updatedAt: OffsetDateTime,
)

data class FleetSnapshot(
    val id: Long,
    val sessionId: Long,
    var leaderOfficerId: Long,
    var factionId: Long,
    var name: String,
    var meta: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
)

data class DiplomacySnapshot(
    val id: Long,
    val sessionId: Long,
    var srcFactionId: Long,
    var destFactionId: Long,
    var stateCode: String,
    var term: Short,
    var isDead: Boolean,
    var isShowing: Boolean,
    var meta: MutableMap<String, Any>,
    var createdAt: OffsetDateTime,
)

data class OfficerTurnSnapshot(
    val id: Long,
    val sessionId: Long,
    val officerId: Long,
    val turnIdx: Short,
    val actionCode: String,
    val arg: MutableMap<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
)

data class FactionTurnSnapshot(
    val id: Long,
    val sessionId: Long,
    val factionId: Long,
    val officerLevel: Short,
    val turnIdx: Short,
    val actionCode: String,
    val arg: MutableMap<String, Any>,
    val brief: String?,
    val createdAt: OffsetDateTime,
)
