server {
    listen       80;
    listen  [::]:80;
    server_name  localhost;

    root /var/www/html;
    index  index.php index.html index.htm;

    #charset koi8-r;
    #access_log  /var/log/nginx/host.access.log  main;

    #error_page  404              /404.html;

    # redirect server error pages to the static page /50x.html
    #
    error_page   500 502 503 504  /50x.html;
    location = /50x.html {
        root   /usr/share/nginx/html;
    }

    location /board {
        root /var/www;
        include snippets/rhymix.conf;
        location ~ \.php$ {
            include        fastcgi_params;
            fastcgi_pass   board:9000;
            fastcgi_index  index.php;
            fastcgi_param  REMOTE_ADDR $http_x_real_ip;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }

    location / {
        include snippets/sam.conf;
        location ~ \.php$ {
            include        fastcgi_params;
            proxy_read_timeout 600;
            fastcgi_pass   app:9000;
            fastcgi_index  index.php;
            fastcgi_param  REMOTE_ADDR $http_x_real_ip;
            fastcgi_param  SCRIPT_FILENAME $document_root$fastcgi_script_name;
        }
    }



    # deny access to .htaccess files, if Apache's document root
    # concurs with nginx's one
    #
    location ~ /\.ht {
        deny  all;
    }
}