location ~ /\.  {
    return 404;
}

location ~ /composer  {
    return 404;
}

location ~ /package\.(json|lock)  {
    return 404;
}


location ~ /d_setting/  {
    return 404;
}

location ~ /d_log/  {
    return 404;
}

location ~ /logs/  {
    return 404;
}

location ~ ^/sam/node_modules  {
    return 404;
}

location ~ ^/sam/vendor/  {
    return 404;
}

location ~ /tests  {
    return 404;
}

location ~ /test-ts  {
    return 404;
}

location ~ /npm_recent  {
    return 404;
}

location ~ /composer_result  {
    return 404;
}

location ~ /tsconfig.json  {
    return 404;
}

location ~ /webpack.config.js  {
    return 404;
}

location ~ /src {
    return 404;
}

location ~ ^/sam/[^/]+/sammo/ {
    return 404;
}

location ~ ^/sam/[^/]+/data/ {
    return 404;
}