package com.openlogh.model

enum class ArmType(val code: Int, val displayName: String) {
    CASTLE(0, "성벽"),
    FOOTMAN(1, "보병"),
    ARCHER(2, "궁병"),
    CAVALRY(3, "기병"),
    WIZARD(4, "귀병"),
    SIEGE(5, "차병"),
    MISC(6, "특수"),
}

enum class ShipClass(
    val code: Int,
    val displayName: String,
    val armType: ArmType,
    val attack: Int,
    val defence: Int,
    val speed: Int,
    val avoid: Int,
    val magicCoef: Double,
    val cost: Int,
    val riceCost: Int,
    val attackCoef: Map<String, Double> = emptyMap(),
    val defenceCoef: Map<String, Double> = emptyMap(),
    val info: List<String> = emptyList(),
    val initSkillTrigger: List<String> = emptyList(),
    val phaseSkillTrigger: List<String> = emptyList(),
    val iActionList: List<String> = emptyList(),
    val reqTech: Int = 0,
    val reqCityNames: Set<String> = emptySet(),
    val reqRegionNames: Set<String> = emptySet(),
    val reqMinRelYear: Int = 0,
) {
    // 성벽
    CASTLE(
        1000,
        "성벽",
        ArmType.CASTLE,
        100,
        100,
        7,
        0,
        0.0,
        99,
        9,
        defenceCoef = mapOf("1" to 1.2),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        reqTech = Int.MAX_VALUE,
    ),

    // 보병
    FOOTMAN(
        1100,
        "보병",
        ArmType.FOOTMAN,
        100,
        150,
        7,
        10,
        0.0,
        9,
        9,
        attackCoef = mapOf("3" to 1.2, "2" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("3" to 0.8, "2" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
    ),
    CHEONGJU(
        1101,
        "청주병",
        ArmType.FOOTMAN,
        100,
        200,
        7,
        10,
        0.0,
        10,
        11,
        attackCoef = mapOf("3" to 1.2, "2" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("3" to 0.8, "2" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
        reqTech = 1000,
        reqRegionNames = setOf("중원"),
    ),
    MARINE(
        1102,
        "수병",
        ArmType.FOOTMAN,
        150,
        150,
        7,
        10,
        0.0,
        11,
        10,
        attackCoef = mapOf("3" to 1.2, "2" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("3" to 0.8, "2" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
        reqTech = 1000,
        reqRegionNames = setOf("오월"),
    ),
    ASSASSIN(
        1103,
        "자객병",
        ArmType.FOOTMAN,
        100,
        150,
        8,
        20,
        0.0,
        10,
        10,
        attackCoef = mapOf("3" to 1.2, "2" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("3" to 0.8, "2" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
        reqTech = 2000,
        reqCityNames = setOf("저"),
    ),
    GUARD(
        1104,
        "근위병",
        ArmType.FOOTMAN,
        150,
        200,
        7,
        10,
        0.0,
        12,
        12,
        attackCoef = mapOf("3" to 1.2, "2" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("3" to 0.8, "2" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
        reqTech = 3000,
        reqCityNames = setOf("낙양"),
    ),
    RATTAN(
        1105,
        "등갑병",
        ArmType.FOOTMAN,
        100,
        225,
        7,
        5,
        0.0,
        13,
        10,
        attackCoef = mapOf("3" to 1.2, "2" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("3" to 0.8, "2" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
        reqTech = 1000,
        reqRegionNames = setOf("남중"),
    ),
    BAEKYI(
        1106,
        "백이병",
        ArmType.FOOTMAN,
        175,
        175,
        7,
        5,
        0.0,
        13,
        11,
        attackCoef = mapOf("3" to 1.1, "2" to 0.9, "5" to 1.1),
        defenceCoef = mapOf("3" to 0.9, "2" to 1.1, "5" to 0.9),
        phaseSkillTrigger = listOf("che_방어력증가5p"),
        reqTech = 3000,
        reqCityNames = setOf("성도"),
    ),

    // 궁병
    ARCHER(
        1200,
        "궁병",
        ArmType.ARCHER,
        100,
        100,
        7,
        10,
        0.0,
        10,
        10,
        attackCoef = mapOf("1" to 1.2, "3" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("1" to 0.8, "3" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
    ),
    MOUNTED_ARCHER(
        1201,
        "궁기병",
        ArmType.ARCHER,
        100,
        100,
        8,
        20,
        0.0,
        11,
        12,
        attackCoef = mapOf("1" to 1.2, "3" to 0.9, "5" to 1.2),
        defenceCoef = mapOf("1" to 0.8, "3" to 1.1, "5" to 0.8),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        reqTech = 1000,
        reqRegionNames = setOf("동이"),
    ),
    CROSSBOW(
        1202,
        "연노병",
        ArmType.ARCHER,
        150,
        100,
        8,
        10,
        0.0,
        12,
        11,
        attackCoef = mapOf("1" to 1.2, "3" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("1" to 0.8, "3" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        reqTech = 1000,
        reqRegionNames = setOf("서촉"),
    ),
    LONGBOW(
        1203,
        "강궁병",
        ArmType.ARCHER,
        150,
        150,
        7,
        10,
        0.0,
        13,
        13,
        attackCoef = mapOf("1" to 1.2, "3" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("1" to 0.8, "3" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        reqTech = 3000,
        reqCityNames = setOf("양양"),
    ),
    STONE_CROSSBOW(
        1204,
        "석궁병",
        ArmType.ARCHER,
        200,
        100,
        7,
        10,
        0.0,
        13,
        13,
        attackCoef = mapOf("1" to 1.2, "3" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("1" to 0.8, "3" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        reqTech = 3000,
        reqCityNames = setOf("건업"),
    ),

    // 기병
    CAVALRY(
        1300,
        "기병",
        ArmType.CAVALRY,
        150,
        100,
        7,
        5,
        0.0,
        11,
        11,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
    ),
    WHITE_HORSE(
        1301,
        "백마병",
        ArmType.CAVALRY,
        200,
        100,
        7,
        5,
        0.0,
        12,
        13,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 1000,
        reqRegionNames = setOf("하북"),
    ),
    HEAVY_CAVALRY(
        1302,
        "중장기병",
        ArmType.CAVALRY,
        150,
        150,
        7,
        5,
        0.0,
        13,
        12,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 1000,
        reqRegionNames = setOf("서북"),
    ),
    CHARGE_CAVALRY(
        1303,
        "돌격기병",
        ArmType.CAVALRY,
        200,
        100,
        8,
        5,
        0.0,
        13,
        11,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 2000,
        reqCityNames = setOf("흉노"),
    ),
    IRON_CAVALRY(
        1304,
        "철기병",
        ArmType.CAVALRY,
        100,
        250,
        7,
        5,
        0.0,
        11,
        13,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 2000,
        reqCityNames = setOf("강"),
    ),
    HUNTER_CAVALRY(
        1305,
        "수렵기병",
        ArmType.CAVALRY,
        150,
        100,
        8,
        15,
        0.0,
        12,
        12,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 2000,
        reqCityNames = setOf("산월"),
    ),
    BEAST(
        1306,
        "맹수병",
        ArmType.CAVALRY,
        250,
        175,
        6,
        0,
        0.0,
        16,
        16,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 2000,
        reqCityNames = setOf("남만"),
    ),
    TIGER_CAVALRY(
        1307,
        "호표기병",
        ArmType.CAVALRY,
        200,
        150,
        7,
        5,
        0.0,
        14,
        14,
        attackCoef = mapOf("2" to 1.2, "1" to 0.8, "5" to 1.2),
        defenceCoef = mapOf("2" to 0.8, "1" to 1.2, "5" to 0.8),
        phaseSkillTrigger = listOf("che_기병병종전투"),
        reqTech = 3000,
        reqCityNames = setOf("허창"),
    ),

    // 귀병
    WIZARD(1400, "귀병", ArmType.WIZARD, 80, 80, 7, 5, 0.5, 9, 9, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8)),
    DIVINE_WIZARD(1401, "신귀병", ArmType.WIZARD, 80, 80, 7, 20, 0.6, 10, 10, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 1000, reqRegionNames = setOf("초")),
    WHITE_WIZARD(1402, "백귀병", ArmType.WIZARD, 80, 130, 7, 5, 0.6, 9, 11, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 2000, reqCityNames = setOf("오환")),
    BLACK_WIZARD(1403, "흑귀병", ArmType.WIZARD, 130, 80, 7, 5, 0.6, 11, 9, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 2000, reqCityNames = setOf("왜")),
    EVIL_WIZARD(1404, "악귀병", ArmType.WIZARD, 130, 130, 7, 0, 0.6, 12, 12, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 3000, reqCityNames = setOf("장안")),
    SOUTH_WIZARD(1405, "남귀병", ArmType.WIZARD, 60, 60, 7, 10, 0.8, 8, 8, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 1000),
    YELLOW_WIZARD(1406, "황귀병", ArmType.WIZARD, 110, 110, 7, 0, 0.8, 13, 10, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 3000, reqCityNames = setOf("낙양")),
    HEAVEN_WIZARD(1407, "천귀병", ArmType.WIZARD, 80, 130, 7, 15, 0.6, 11, 12, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 3000, reqCityNames = setOf("성도")),
    DEMON_WIZARD(1408, "마귀병", ArmType.WIZARD, 130, 80, 7, 15, 0.6, 12, 11, attackCoef = mapOf("5" to 1.2), defenceCoef = mapOf("5" to 0.8), reqTech = 3000, reqCityNames = setOf("업")),

    // 차병(공성)
    JEONGRAN(
        1500,
        "정란",
        ArmType.SIEGE,
        100,
        100,
        6,
        0,
        0.0,
        14,
        5,
        attackCoef = mapOf("1" to 1.25, "2" to 1.25, "3" to 1.25, "4" to 1.25, "0" to 1.8, "1106" to 1.112),
        defenceCoef = mapOf("1" to 1.2, "2" to 1.2, "3" to 1.2, "4" to 1.2, "1106" to 1.067),
        initSkillTrigger = listOf("che_성벽부상무효"),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        iActionList = listOf("che_성벽선제"),
        reqMinRelYear = 3,
    ),
    RAM(
        1501,
        "충차",
        ArmType.SIEGE,
        150,
        100,
        6,
        0,
        0.0,
        18,
        5,
        attackCoef = mapOf("1" to 0.8, "2" to 0.8, "3" to 0.8, "4" to 0.8, "0" to 2.4),
        defenceCoef = mapOf("1" to 1.2, "2" to 1.2, "3" to 1.2, "4" to 1.2),
        initSkillTrigger = listOf("che_성벽부상무효"),
        reqTech = 1000,
        reqMinRelYear = 3,
    ),
    CATAPULT(
        1502,
        "벽력거",
        ArmType.SIEGE,
        150,
        100,
        6,
        5,
        0.0,
        20,
        5,
        attackCoef = mapOf("1" to 1.25, "2" to 1.25, "3" to 1.25, "4" to 1.25, "0" to 1.8, "1106" to 1.112),
        defenceCoef = mapOf("1" to 1.2, "2" to 1.2, "3" to 1.2, "4" to 1.2, "1106" to 1.067),
        initSkillTrigger = listOf("che_성벽부상무효"),
        phaseSkillTrigger = listOf("che_선제사격시도", "che_선제사격발동"),
        iActionList = listOf("che_성벽선제"),
        reqTech = 3000,
        reqCityNames = setOf("업"),
    ),
    WOODEN_OX(
        1503,
        "목우",
        ArmType.SIEGE,
        50,
        200,
        5,
        0,
        0.0,
        15,
        5,
        attackCoef = mapOf("1" to 1.0, "2" to 1.0, "3" to 1.0, "4" to 1.0, "0" to 1.8),
        defenceCoef = mapOf("1" to 1.0, "2" to 1.0, "3" to 1.0, "4" to 1.0, "1106" to 1.0),
        initSkillTrigger = listOf("che_성벽부상무효"),
        phaseSkillTrigger = listOf("che_저지시도", "che_저지발동"),
        reqTech = 3000,
        reqCityNames = setOf("성도"),
    );

    fun getAttackCoef(opponent: ShipClass): Double {
        return attackCoef[opponent.code.toString()]
            ?: attackCoef[opponent.armType.code.toString()]
            ?: 1.0
    }

    fun getDefenceCoef(opponent: ShipClass): Double {
        return defenceCoef[opponent.code.toString()]
            ?: defenceCoef[opponent.armType.code.toString()]
            ?: 1.0
    }

    fun getShortName(): String = if (displayName.length <= 4) displayName else displayName.take(4)

    fun isValidForNation(
        ownCityNames: Set<String>,
        ownRegionIds: Set<Int>,
        relYear: Int,
        tech: Int,
        regionNameToId: Map<String, Int> = REGION_MAP,
    ): Boolean {
        if (reqTech > 0 && tech < reqTech) return false
        if (reqMinRelYear > 0 && relYear < reqMinRelYear) return false
        if (reqCityNames.isNotEmpty() && reqCityNames.none { it in ownCityNames }) return false
        if (reqRegionNames.isNotEmpty()) {
            val reqRegionIds = reqRegionNames.mapNotNull { regionNameToId[it] }
            if (reqRegionIds.none { it in ownRegionIds }) return false
        }
        return true
    }

    fun pickScore(tech: Int): Double {
        val armPerPhase = 500.0
        val techAbil = (tech / 1000) * 25.0
        var score = armPerPhase + attack + defence + techAbil * 2
        score *= (1.0 + speed / 2.0)
        score /= maxOf(1.0 - avoid / 100.0, 0.1)
        score *= (1.0 + magicCoef / 2.0)
        return score
    }

    companion object {
        private val byCode = entries.associateBy { it.code }
        private val REGION_MAP = mapOf(
            "하북" to 1, "중원" to 2, "서북" to 3, "서촉" to 4,
            "남중" to 5, "초" to 6, "오월" to 7, "동이" to 8,
        )

        fun fromCode(code: Int): ShipClass? = byCode[code]
        fun byArmType(armType: ArmType): List<ShipClass> = entries.filter { it.armType == armType }
    }
}
