ALTER TABLE general ADD COLUMN pos_x REAL NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN pos_y REAL NOT NULL DEFAULT 0;
ALTER TABLE general ADD COLUMN dest_x REAL;
ALTER TABLE general ADD COLUMN dest_y REAL;
